### PR TITLE
[hover] Fix universe printing in hover.

### LINKED ISSUE #835: Unvierse levels displayed as de bruijin indices in hover
When hovering over a term with `Set Printing Universes`, we expect to see nicely named universe variables.
```coq
From Coq Require Import Prelude.
Set Printing Universes.
Set Universe Polymorphism.

Inductive foo : Type := bar : Type -> foo.

Print foo.
```

Here `Print` outputs the following:
```coq
Inductive foo@{u} : Type@{u+1} :=  bar : Type@{u} -> foo@{u}.
(* u |=  *)

Arguments bar _%type_scope
```
Which is reasonable. However hovering over `foo` outputs:
```coq
foo : Type@{Var(0)+1}
```
which is not very readable. Since `About` and `Print` are able to provide reasonable terms, it seems there is some configuration missing in the term printer.

### PR DESCRIPTION
**Pull request by ejgallego**
Our code was incomplete. The API here could be really improved Coq-side. About is too verbose for hover, hence our code. We could opt for the version in `prettyp.ml` tho.

Fixes #835

### CODE REVIEW

**Comment by Alizter** [comment]
How does the new version print?

File: controller/rq_hover.ml [hunk 1]
```diff
@@ -128,10 +162,11 @@ let pp_file fmt = function
   | Some file -> Format.fprintf fmt " - **in file**: `%s`" file
 
 let pp_typ id = function
-  | Def (typ, cr, file) ->
+  | Def (typ, param, cr, file) ->
```
Comment (Alizter) [inline controller/rq_hover.ml:165]: Probably best to call this `sort_param` or something.

**Comment by ejgallego** [comment]
```coq
foo@{u u0 u1} (M : Type@{u}) : Type@{u0} -> Type@{max(u,u1+1)}
```

File: controller/rq_hover.ml [hunk 2]
```diff
@@ -12,10 +12,21 @@ let build_ind_type mip = Inductive.type_of_inductive mip
 
 type id_info =
   | Notation of Pp.t
-  | Def of (Pp.t * Names.Constant.t option * string option)
+  | Def of (Pp.t * Pp.t * Names.Constant.t option * string option)
```
Comment (Alizter) [inline controller/rq_hover.ml:15]: Might be a good idea to make this a record and give it some proper field names. It would make it easier to read and understand.

Comment (ejgallego) [reply controller/rq_hover.ml:15]: All the code here was mostly placeholder as to test hover and wasn't properly designed, however it seems we got stuck with it for a while, due to other priorities.

If you look at the code, it is indeed pretty horrible haha. The Coq API doesn't absolutely help tho.

Comment (Alizter) [reply controller/rq_hover.ml:15]: Yeah, we should really try to upstream some better API changes on the Coq side. I believe it isn't considered a priority due to the mostly internal nature.

**Review by Alizter — APPROVED** [review]
Seems like a fine patch for user experience, but the API could use a cleanup here and upstream.

File: controller/rq_hover.ml [hunk 3]
```diff
@@ -12,10 +12,28 @@ let build_ind_type mip = Inductive.type_of_inductive mip
...
-  | Def of (Pp.t * Names.Constant.t option * string option)
-
-let info_of_ind env sigma ((sp, i) : Names.Ind.t) =
+  | Def of
+      { typ : Pp.t  (** type of the ide *)
+      ; params : Pp.t  (** params that need display next to the name *)
+      ; full_path : Names.Constant.t option
+            (** full path of the constant, if any, for example
+                [Stdlib.Lists.map] *)
+      ; file : string option  (** filename where the constant is located *)
```
Comment (Alizter) [inline controller/rq_hover.ml:21]: Do we have access to the location too? (The one goto definition uses). Not relevant for this PR, but it might be useful to include.

Comment (ejgallego) [reply controller/rq_hover.ml:21]: We could, but not sure line number is relevant here, the client can indeed issue the corresponding specific request for location.
